Times:
    COOKED_MUTTON: 15
    APPLE: 5
    BAKED_POTATO: 5
    BEETROOT: 5
    BEETROOT_SOUP: 15
    BREAD: 15
    CARROT: 5
    COOKED_CHICKEN: 15
    COOKED_COD: 15
    COOKED_PORKCHOP: 15
    COOKED_RABBIT: 15
    COOKIE: 5
    DRIED_KELP: 5
    MELON_SLICE: 5
    POTATO: 5
    COOKED_BEEF: 15
    SWEET_BERRIES: 5
